# Set the prompt.
export PS1="$USER \w \[$(tput setaf 5)\]>\[$(tput sgr0)\]"

# Set nvim as editor.
export EDITOR="nvim"

# Add ~/bin to path
PATH="$PATH:$HOME/bin"

# Execute global npm packages as commands
PATH="$PATH:$HOME/bin/npm-global/bin"

# Set XDG_CONFIG_HOME
export XDG_CONFIG_HOME="${HOME}/.config"

# History completion.
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

# Don't log duplicate commands.
export HISTCONTROL=ignoredups

# Check window size after every command
shopt -s checkwinsize

# Enable extended globbing allowing composite patterns
shopt -s extglob

# ALIASES
if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# git hub autocompletions
if [ -f ~/dotfiles/git/.hub.bash_completion ]; then
  source ~/dotfiles/git/.hub.bash_completion
fi

if [ "$HOSTNAME" = archy ]; then
	export MONITOR1="DVI-I-1"
	export MONITOR2="DVI-D-0"
else
	export MONITOR1="DP-2"
	export MONITOR2="DP-4"
fi

# Source colors generated by wal
source "$HOME/.cache/wal/colors.sh"

# Import colorscheme from 'wal'
[[ -z "$VTE_VERSION" ]] && (wal -r &)

# Source git autocompletions
source /usr/share/bash-completion/completions/git

umask 027
